query_properties = {1: {"LINEITEM": {"L_SHIPDATE": "r"}},
              2: {"PART": {"P_SIZE": "e", "P_TYPE": "c"}, "PARTSUPP": {"PS_SUPPKEY": "j", "PS_PARTKEY": "j"},
                  "SUPPLIER": {"S_NATIONKEY": "j"}, "NATION": {"N_REGIONKEY": "j"}, "REGION": {"R_NAME": "e"}},
              3: {"ORDERS": {"O_CUSTKEY": "j", "O_ORDERDATE": "r"}, "CUSTOMER": {"C_MKTSEGMENT": "e"}, "LINEITEM":
                  {"L_SHIPDATE": "r", "L_ORDERKEY": "j"}},
              4: {"ORDERS": {"O_ORDERKEY": "jpk", "O_ORDERDATE": "r"}, "LINEITEM":
                  {"L_ORDERKEY": "jpk", "L_COMMITDATE": "c", "L_RECEIPTDATE": "c"}},
              5: {"ORDERS": {"O_CUSTKEY": "j", "O_ORDERKEY": "jpk", "O_ORDERDATE": "r"},
                  "LINEITEM": {"L_ORDERKEY": "jpk", "L_SUPPKEY": "j"},
                  "CUSTOMER": {"C_CUSTKEY": "jpk", "C_NATIONKEY": "j"},
                  "SUPPLIER": {"S_NATIONKEY": "j", "S_SUPPKEY": "jpk"},
                  "NATION": {"N_NATIONKEY": "jpk", "N_REGIONKEY": "j"},
                  "REGION": {"R_REGIONKEY": "jpk", "R_NAME": "e"}},
              6: {"LINEITEM": {"L_SHIPDATE": "r", "L_DISCOUNT": "r", "L_QUANTITY": "r"}},
              7: {"ORDERS": {"O_CUSTKEY": "j", "O_ORDERKEY": "jpk"},
                  "LINEITEM": {"L_ORDERKEY": "jpk", "L_SUPPKEY": "j", "L_SHIPDATE": "r"},
                  "CUSTOMER": {"C_CUSTKEY": "jpk", "C_NATIONKEY": "j"},
                  "SUPPLIER": {"S_NATIONKEY": "j", "S_SUPPKEY": "jpk"},
                  "NATION": {"N_NATIONKEY": "jpk", "N_NAME": "e"}},
              8: {"ORDERS": {"O_CUSTKEY": "j", "O_ORDERKEY": "jpk", "O_ORDERDATE": "r"},
                  "LINEITEM": {"L_ORDERKEY": "jpk", "L_SUPPKEY": "j", "L_PARTKEY": "j"},
                  "CUSTOMER": {"C_CUSTKEY": "jpk", "C_NATIONKEY": "j"},
                  "SUPPLIER": {"S_NATIONKEY": "j", "S_SUPPKEY": "jpk"},
                  "NATION": {"N_NATIONKEY": "jpk", "N_REGIONKEY": "j"},
                  "REGION": {"R_REGIONKEY": "jpk", "R_NAME": "e"}, "PART": {"P_PARTKEY": "jpk", "P_TYPE": "e"}},
              9: {"PART": {"P_PARTKEY": "jpk", "P_NAME": "c"}, "SUPPLIER": {"S_NATIONKEY": "j", "S_SUPPKEY": "jpk"},
                  "LINEITEM": {"L_ORDERKEY": "jpk", "L_SUPPKEY": "j", "L_PARTKEY": "j"},
                  "PARTSUPP": {"PS_SUPPKEY": "jpk2", "PS_PARTKEY": "jpk"}, "ORDERS": {"O_ORDERKEY": "jpk"},
                  "NATION": {"N_NATIONKEY": "jpk"}},
              10: {"ORDERS": {"O_CUSTKEY": "j", "O_ORDERKEY": "jpk", "O_ORDERDATE": "r"},
                   "LINEITEM": {"L_ORDERKEY": "jpk", "L_RETURNFLAG": "e"},
                   "CUSTOMER": {"C_CUSTKEY": "jpk", "C_NATIONKEY": "j"}, "NATION": {"N_NATIONKEY": "jpk"}},
              11: {"PARTSUPP": {"PS_SUPPKEY": "jpk2"}, "SUPPLIER": {"S_SUPPKEY": "jpk", "S_NATIONKEY": "j"},
                   "NATION": {"N_NATIONKEY": "jpk", "N_NAME": "e"}},
              12: {"ORDERS": {"O_ORDERKEY": "jpk"},
                   "LINEITEM": {"L_ORDERKEY": "jpk", "L_SHIPMODE": "e", "L_RECEIPTDATE": "r",
                                "L_SHIPDATE": "r", "L_COMMITDATE": "r"}},
              13: {"CUSTOMER": {"C_CUSTKEY": "jpk"}, "ORDERS": {"O_COMMENT": "c", "O_CUSTKEY": "j"}},
              14: {"LINEITEM": {"L_SHIPDATE": "r", "L_PARTKEY": "j"}, "PART": {"P_PARTKEY": "jpk"}},
              16: {"PARTSUPP": {"PS_PARTKEY":"jpk", "PS_SUPPKEY":"jpk2"},
                   "PART": {"P_PARTKEY": "jpk", "P_SIZE": "e", "P_BRAND": "r", "P_TYPE": "c"},
                   "SUPPLIER": {"S_COMMENT":"c"}},
              17: {"PART": {"P_PARTKEY": "jpk", "P_CONTAINER": "e", "P_BRAND": "e"}, "LINEITEM": {"L_PARTKEY": "j"}},
              18: {"ORDERS": {"O_CUSTKEY": "j", "O_ORDERKEY": "jpk"}, "CUSTOMER": {"C_CUSTKEY": "jpk"},
                   "LINEITEM": {"L_ORDERKEY": "jpk"}},
              19: {"LINEITEM": {"L_SHIPMODE": "e", "L_PARTKEY": "j", "L_QUANTITY": "r", "L_SHIPINSTRUCT": "e"},
                   "PART": {"P_SIZE": "r", "P_PARTKEY": "jpk", "P_BRAND": "e", "P_CONTAINER": "e"}},
              20: {"SUPPLIER": {"S_SUPPKEY": "jpk", "S_NATIONKEY": "j"},
                   "PARTSUPP": {"PS_PARTKEY": "jpk", "PS_AVAILQTY": "r", "PS_SUPPKEY": "jpk2"},
                   "LINEITEM": {"L_SUPPKEY": "j", "L_PARTKEY": "j", "L_SHIPDATE": "r"},
                   "NATION": {"N_NATIONKEY": "jpk", "N_NAME": "e"}, "PART": {"P_NAME": "r"}},
              21: {"SUPPLIER": {"S_SUPPKEY": "jpk", "S_NATIONKEY": "j"},
                   "ORDERS": {"O_ORDERKEY": "jpk", "O_ORDERSTATUS": "e"},
                   "LINEITEM": {"L_SUPPKEY": "j", "L_ORDERKEY": "jpk", "L_RECEIPTDATE": "c", "L_COMMITDATE": "c"},
                   "NATION": {"N_NATIONKEY": "jpk", "N_NAME": "e"}},
              22: {"CUSTOMER": {"C_ACCTBAL": "r", "C_PHONE": "c", "C_CUSTKEY": "jpk"}, "ORDERS": {"O_CUSTKEY": "j"}},
 'payload': {1: {"LINEITEM": ["L_RETURNFLAG", "L_LINESTATUS", "L_QUANTITY", "L_EXTENDEDPRICE", "L_DISCOUNT", "L_TAX"]},
            2: {"SUPPLIER": ["S_ACCTBAL", "S_NAME", "S_ADDRESS", "S_PHONE", "S_COMMENT"], "NATION": ["N_NAME"], "PART":
                ["P_PARTKEY", "P_MFGR"], "PARTSUPP": ["PS_SUPPLYCOST"]},
            3: {"LINEITEM": ["L_ORDERKEY", "L_EXTENDEDPRICE", "L_DISCOUNT"], "ORDERS": ["O_ORDERDATE",
                                                                                        "O_SHIPPRIORITY"]},
            4: {"ORDERS": ["O_ORDERPRIORITY"]},
            5: {"NATION": ["N_NAME"], "LINEITEM": ["L_EXTENDEDPRICE", "L_DISCOUNT"]},
            6: {"LINEITEM": ["L_EXTENDEDPRICE", "L_DISCOUNT"]},
            7: {"LINEITEM": ["L_SHIPDATE", "L_EXTENDEDPRICE", "L_DISCOUNT"], "NATION": ["N_NAME"]},
            8: {"ORDERS": ["O_ORDERDATE"], "LINEITEM": ["L_EXTENDEDPRICE", "L_DISCOUNT"], "NATION": ["N_NAME"]},
            9: {"ORDERS": ["O_ORDERDATE"], "LINEITEM": ["L_EXTENDEDPRICE", "L_DISCOUNT", "L_QUANTITY"], "PARTSUPP":
                ["PS_SUPPLYCOST"], "NATION": ["N_NAME"]},
            10: {"CUSTOMER": ["C_CUSTKEY", "C_NAME", "C_ACCTBAL", "C_ADDRESS", "C_PHONE", "C_COMMENT"], "LINEITEM":
                ["L_EXTENDEDPRICE", "L_DISCOUNT"], "NATION": ["N_NAME"]},
            11: {"PARTSUPP": ["PS_PARTKEY", "PS_SUPPLYCOST", "PS_AVAILQTY"]},
            12: {"LINEITEM": ["L_SHIPMODE"], "ORDERS": ["O_ORDERPRIORITY"]},
            13: {"CUSTOMER": ["C_CUSTKEY"], "ORDERS": ["O_ORDERKEY"]},
            14: {"PART": ["P_TYPE"], "LINEITEM": ["L_EXTENDEDPRICE", "L_DISCOUNT"]},
            16: {"PART": ["P_BRAND", "P_TYPE", "P_SIZE"]},
            17: {"LINEITEM": ["L_EXTENDEDPRICE", "L_QUANTITY"]},
            18: {"CUSTOMER": ["C_NAME"], "ORDERS": ["O_ORDERDATE", "O_TOTALPRICE"], "LINEITEM": ["L_QUANTITY"]},
            19: {"LINEITEM": ["L_EXTENDEDPRICE", "L_DISCOUNT"]},
            20: {"SUPPLIER": ["S_NAME", "S_ADDRESS"], "LINEITEM": ["L_QUANTITY"]},
            21: {"SUPPLIER": ["S_NAME"]},
            22: {"CUSTOMER": ["C_PHONE", "C_ACCTBAL"]}},
 'tables': {1: ['store_returns', 'customer', 'date_dim', 'store'],
            2: ['catalog_sales', 'web_sales', 'date_dim'],
            3: ['date_dim', 'item'],
            4: ['store_sales', 'catalog_sales', 'web_sales', 'customer', 'date_dim'],
            5: ['store_sales',
                'catalog_sales',
                'web_sales',
                'store_returns',
                'catalog_returns',
                'web_returns',
                'catalog_page',
                'web_site',
                'store'],
            6: ['customer', 'date_dim', 'customer_address', 'item'],
            7: ['store_sales', 'customer_demographics', 'date_dim', 'item', 'promotion'],
            8: ['store_sales', 'customer', 'date_dim', 'customer_address', 'store'],
            9: ['store_sales'],
            10: ['catalog_sales', 'web_sales', 'customer', 'customer_demographics', 'date_dim', 'customer_address'],
            11: ['store_sales', 'web_sales', 'customer', 'date_dim'],
            12: ['web_sales', 'item'],
            13: ['store_sales',
                 'customer_demographics',
                 'date_dim',
                 'customer_address',
                 'household_demographics',
                 'store'],
            14: ['store_sales', 'catalog_sales', 'web_sales', 'date_dim', 'item'],
            15: ['catalog_sales', 'customer', 'date_dim', 'customer_address'],
            16: ['catalog_sales', 'catalog_returns', 'customer_address', 'call_center'],
            17: ['store_sales', 'catalog_sales', 'store_returns', 'date_dim', 'item', 'store'],
            18: ['catalog_sales', 'customer', 'customer_demographics', 'date_dim', 'customer_address', 'item'],
            19: ['customer', 'date_dim', 'customer_address', 'item', 'store'],
            20: ['catalog_sales', 'item'],
            21: ['inventory', 'item', 'warehouse'],
            22: ['inventory', 'date_dim', 'item'],
            23: ['store_sales', 'date_dim', 'item'],
            24: ['store_sales', 'customer', 'customer_address', 'item', 'store'],
            25: ['store_sales', 'catalog_sales', 'store_returns', 'date_dim', 'item', 'store'],
            26: ['catalog_sales', 'customer_demographics', 'date_dim', 'item', 'promotion'],
            27: ['store_sales', 'customer_demographics', 'date_dim', 'item', 'store'],
            28: ['store_sales'],
            29: ['store_sales', 'catalog_sales', 'store_returns', 'date_dim', 'item', 'store'],
            30: ['web_returns', 'customer', 'date_dim', 'customer_address'],
            31: ['web_sales', 'date_dim', 'customer_address'],
            32: ['catalog_sales', 'item'],
            33: ['catalog_sales', 'web_sales', 'date_dim', 'customer_address', 'item'],
            34: ['store_sales', 'customer', 'date_dim', 'household_demographics', 'store'],
            35: ['catalog_sales', 'web_sales', 'customer', 'customer_demographics', 'date_dim', 'customer_address'],
            36: ['store_sales', 'date_dim', 'item', 'store'],
            37: ['catalog_sales', 'inventory', 'item'],
            38: ['catalog_sales', 'web_sales', 'customer', 'date_dim'],
            39: ['inventory', 'date_dim', 'item', 'warehouse'],
            40: ['catalog_sales', 'catalog_returns', 'item', 'warehouse'],
            41: ['item'],
            42: ['date_dim', 'item'],
            43: ['store_sales', 'date_dim', 'store'],
            44: ['store_sales'],
            45: ['web_sales', 'customer', 'date_dim', 'customer_address', 'item'],
            46: ['store_sales', 'customer', 'date_dim', 'customer_address', 'household_demographics', 'store'],
            47: ['store_sales', 'date_dim', 'item', 'store'],
            48: ['store_sales', 'customer_demographics', 'date_dim', 'customer_address', 'store'],
            49: ['store_sales',
                 'catalog_sales',
                 'web_sales',
                 'store_returns',
                 'catalog_returns',
                 'web_returns',
                 'date_dim'],
            50: ['store_returns', 'date_dim', 'store'],
            51: ['store_sales', 'web_sales', 'date_dim'],
            52: ['date_dim', 'item'],
            53: ['date_dim', 'item', 'store'],
            54: ['customer', 'date_dim', 'customer_address', 'item', 'store'],
            55: ['date_dim', 'item'],
            56: ['catalog_sales', 'date_dim', 'customer_address', 'item'],
            57: ['catalog_sales', 'date_dim', 'item', 'call_center'],
            58: ['catalog_sales', 'item'],
            59: ['store_sales', 'date_dim', 'store'],
            60: ['catalog_sales', 'web_sales', 'date_dim', 'customer_address', 'item'],
            61: ['store_sales', 'customer', 'date_dim', 'customer_address', 'item', 'promotion', 'store'],
            62: ['web_sales', 'date_dim', 'web_site', 'ship_mode', 'warehouse'],
            63: ['date_dim', 'item', 'store'],
            64: ['catalog_sales',
                 'store_returns',
                 'catalog_returns',
                 'customer',
                 'customer_demographics',
                 'date_dim',
                 'customer_address',
                 'item',
                 'household_demographics',
                 'promotion',
                 'income_band',
                 'store'],
            65: ['store_sales', 'date_dim', 'item', 'store'],
            66: ['catalog_sales', 'time_dim', 'date_dim', 'ship_mode', 'warehouse'],
            67: ['store_sales', 'date_dim', 'item', 'store'],
            68: ['store_sales', 'customer', 'date_dim', 'household_demographics', 'store'],
            69: ['catalog_sales', 'web_sales', 'customer', 'customer_demographics', 'date_dim', 'customer_address'],
            70: ['store_sales', 'date_dim', 'store'],
            71: ['store_sales', 'catalog_sales', 'web_sales', 'time_dim', 'date_dim', 'item'],
            72: ['catalog_sales', 'inventory', 'customer_demographics', 'date_dim', 'item', 'promotion', 'warehouse'],
            73: ['customer', 'date_dim', 'household_demographics', 'store'],
            74: ['store_sales', 'web_sales', 'customer', 'date_dim'],
            75: ['store_sales', 'catalog_sales', 'store_returns', 'catalog_returns', 'web_returns', 'date_dim', 'item'],
            76: ['store_sales', 'catalog_sales', 'web_sales', 'date_dim', 'item'],
            77: ['store_sales',
                 'catalog_sales',
                 'web_sales',
                 'store_returns',
                 'catalog_returns',
                 'web_returns',
                 'web_page',
                 'store'],
            78: ['store_sales',
                 'catalog_sales',
                 'web_sales',
                 'store_returns',
                 'catalog_returns',
                 'web_returns',
                 'date_dim'],
            79: ['store_sales', 'customer', 'date_dim', 'household_demographics', 'store'],
            80: ['catalog_sales',
                 'store_returns',
                 'catalog_returns',
                 'web_returns',
                 'item',
                 'catalog_page',
                 'promotion',
                 'web_site',
                 'store'],
            81: ['catalog_returns', 'customer', 'date_dim', 'customer_address'],
            82: ['inventory', 'item'],
            83: ['store_returns', 'catalog_returns', 'web_returns', 'item'],
            84: ['store_returns', 'customer', 'customer_demographics', 'household_demographics', 'income_band'],
            85: ['web_sales',
                 'web_returns',
                 'customer_demographics',
                 'date_dim',
                 'customer_address',
                 'web_page',
                 'reason'],
            86: ['date_dim', 'item'],
            87: ['catalog_sales', 'web_sales', 'date_dim'],
            88: ['store_sales', 'time_dim', 'household_demographics', 'store'],
            89: ['date_dim', 'item', 'store'],
            90: ['web_sales', 'time_dim', 'household_demographics', 'web_page'],
            91: ['catalog_returns',
                 'customer',
                 'customer_demographics',
                 'date_dim',
                 'customer_address',
                 'household_demographics',
                 'call_center'],
            92: ['web_sales', 'item'],
            93: ['store_sales', 'store_returns', 'reason'],
            94: ['web_sales', 'web_returns', 'customer_address', 'web_site'],
            95: ['web_sales', 'web_returns', 'customer_address', 'web_site'],
            96: ['store_sales', 'time_dim', 'household_demographics', 'store'],
            97: ['catalog_sales', 'date_dim'],
            98: ['item'],
            99: ['catalog_sales', 'date_dim', 'ship_mode', 'call_center', 'warehouse']},
        'gb_payload': {1: {}, 2: {}, 3: {}, 4: {}, 5: {}, 6: {}, 7: {}, 8: {}, 9: {}, 10: {}, 11: {},
                       12: {}, 13: {}, 14: {}, 15: {}, 16: {}, 17: {}, 18: {}, 19: {}, 20: {}, 21: {},
                       22: {}, 23: {}, 24: {}, 25: {}, 26: {}, 27: {}, 28: {}, 29: {}, 30: {}, 31: {},
                       32: {}, 33: {}, 34: {}, 35: {}, 36: {}, 37: {}, 38: {}, 39: {}, 40: {}, 41: {},
                       42: {}, 43: {}, 44: {}, 45: {}, 46: {}, 47: {}, 48: {}, 49: {}, 50: {}, 51: {},
                       52: {}, 53: {}, 54: {}, 55: {}, 56: {}, 57: {}, 58: {}, 59: {}, 60: {}, 61: {},
                       62: {}, 63: {}, 64: {}, 65: {}, 66: {}, 67: {}, 68: {}, 69: {}, 70: {}, 71: {},
                       72: {}, 73: {}, 74: {}, 75: {}, 76: {}, 77: {}, 78: {}, 79: {}, 80: {}, 81: {},
                       82: {}, 83: {}, 84: {}, 85: {}, 86: {}, 87: {}, 88: {}, 89: {}, 90: {}, 91: {},
                       92: {}, 93: {}, 94: {}, 95: {}, 96: {}, 97: {}, 98: {}, 99: {}},
        'dim_tables': {}}
